### ISSUE TITLE
Don't call it an app store

### ISSUE THREAD

**Issue by paulproteus** [tableflip/sandstorm-appstore#233]
Unless @kentonv or @jadeqwang says otherwise, I think we should consistently call this the "app marketplace", including the github repo name and CSS classes and the HTML title.

Curious for their opinion. I don't think this is urgent yet, but it'd be nice to get this done sooner rather than later if we agree it's important.

**Comment by ocdtrekkie** [comment]
That is probably a decent choice. Apple has expressed belief they own the phrase "App store" before. And Android abandoned the "market" language.

**Comment by jparyani** [comment]
It is worth noting that Apple lost the case when trying to enforce their trademark https://en.wikipedia.org/wiki/App_store#.22App_Store.22_trademark.

**Comment by paulproteus** [comment]
Oh wow, that is awesome to hear, @jparyani -- I didn't realize that.

I no longer have any opinion about if this is important, so I will close it for now, but if others want me to re-open, I can.

**Comment by ocdtrekkie** [comment]
I was pretty sure they lost, but 'app store'  does tend to be heavily used. I suppose it's just a branding choice.

**Comment by ocdtrekkie** [comment]
I can think of a marketplace at an oasis in a desert more than I think of a store at an oasis in a desert? Or a bazaar?

**Comment by kentonv** [comment]
FWIW, I would like to avoid "app store" in any formal messaging. It's not really a "store" anyhow as we aren't going to do payments through it...
